### ISSUE TITLE
Issues in working with services when Device name is used to open

### ISSUE THREAD

**Issue by JDogHerman** [sensboston/BLEConsole#11] opened 2021-04-14 17:36 UTC
I am attempting to leverage BLEConsole in a scripted method. Issue I am having is that when leveraging the open command against the name of the devices the application presents the services as it should but any time I attempt to write to those characteristics or set the service I get an error. When specifying the device by number I am able to connect without issue. This is an issue as if the system device order changes the script will break. 

A successful write...
```
BLE: ls
#00: bhyve_20B160
#01: Living Room TV
#02: MX Master 2S
#03: NEEWER-RGB660 PRO
BLE: open #3
Connecting to NEEWER-RGB660 PRO.
Found 4 services:
#00: GenericAccess
#01: GenericAttribute
#02: Custom Service: 69400001-b5a3-f393-e0a9-e50e24dcca99
#03: Custom Service: 7f510004-b5a3-f393-e0a9-e50e24dcca9e
BLE: set #2
Selected service Custom Service: 69400001-b5a3-f393-e0a9-e50e24dcca99.
#00: Custom Characteristic: 69400003-b5a3-f393-e0a9-e50e24dcca99          N
#01: Custom Characteristic: 69400002-b5a3-f393-e0a9-e50e24dcca99         W
BLE: format HEX
Current display format: Hex
BLE: w #02/#01 78 86 04 58 01 18 64 D7
```

An example of write failure... showing the error "Error accessing service." & "Please specify characteristic name or # for writing."
```
BLE: ls
#00: bhyve_20B160
#01: Living Room TV
#02: MX Master 2S
#03: NEEWER-RGB660 PRO
BLE: open NEEWER-RGB660
Device NEEWER-RGB660 PRO is disconnected.
Connecting to NEEWER-RGB660 PRO.
Found 4 services:
#00: GenericAccess
#01: GenericAttribute
#02: Custom Service: 69400001-b5a3-f393-e0a9-e50e24dcca99
#03: Custom Service: 7f510004-b5a3-f393-e0a9-e50e24dcca9e
BLE: set #2
Error accessing service.
BLE: format HEX
Current display format: Hex
BLE: w #02/#01 78 86 04 58 01 18 64 D7
Please specify characteristic name or # for writing.
```

**Comment by sensboston** [comment] 2021-04-26 06:10
@JDogHerman, I think "Device NEEWER-RGB660 PRO is disconnected." in your log is a main reason of failure. Sorry, I can't trace what's really happened, but you're have all abilities to test & try.

**Comment by JDogHerman** [comment] 2021-04-26 15:03
When I issue an open command to an already opened device I get the disconnect message then the connected message. This is because the device only links to one host.

The issue is when attempting to open based on name and NOT instance number the app errors out saying "error accessing service."

**Comment by sensboston** [comment] 2021-04-27 16:45
Sorry, can't reproduce on my side: just tried but everything is working as expected

`
BLE: ls
#00: Echo Dot-HT2
#01: F2
#02: TYME - 662B
BLE: open Echo
Device Echo Dot-HT2 is disconnected.
Connecting to Echo Dot-HT2.
Found 4 services:
#00: GenericAttribute
#01: GenericAccess
#02: 65024
#03: DeviceInformation
BLE: open Echo
Device Echo Dot-HT2 is disconnected.
Connecting to Echo Dot-HT2.
Found 4 services:
#00: GenericAttribute
#01: GenericAccess
#02: 65024
#03: DeviceInformation
BLE: read #3/#0
Amazon
BLE:
`

**Comment by JDogHerman** [comment] 2021-04-27 17:02
Is there a logging method that can be enabled? I had wondered if it was related to non-alphanumeric characters in the device name.

**Comment by sensboston** [comment] 2021-04-27 22:55
Sorry, logging isn't implemented. BTW, it's an open source software. If you even don't have an experience working with Visual Studio and C# at all, you're still good to go: download & install free [Visual Studio Community](https://visualstudio.microsoft.com/vs/community/), clone code with **git** (or you may just download & unpack solution archive), open (in VS) solution file **BLEConsole.sln** and press F5.
Debugging in source code is a real beauty, way better than any log file.

**Comment by sensboston** [comment] 2021-05-10 01:31
@JDogHerman I'll going to close this issue if you have nothing to add. Hope, you're resolved it by changing the BLE device name (of course if you're developed this device).

**Comment by sensboston** [comment] 2021-06-16 04:51
Closed by time-out ;)

**Closed** 2021-06-16 04:50 UTC
